name: Easy
options:
  bundleIdPrefix: com.ghost
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  groupSortPosition: top

settings:
  SWIFT_VERSION: "6.0"
  DEVELOPMENT_TEAM: ""
  CODE_SIGN_STYLE: Automatic

targets:
  Easy:
    type: application
    platform: iOS
    sources:
      - Easy
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ghost.easy
      INFOPLIST_FILE: Easy/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Easy/Easy.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.device.camera: true
        com.apple.security.network.client: true
